FROM ubuntu:focal-20200720

LABEL maintainer="Wildlife Studios"

ARG CURL_VERSION=7.68.0-1ubuntu2.1
ARG GIT_VERSION=1:2.25.1-1ubuntu3
ARG JQ_VERSION=1.6-1
ARG ZIP_VERSION=3.0-11build1
ARG MAKE_VERSION=4.2.1-1.2


ARG VAULT_VERSION=1.3.4
ARG TFENV_VERSION=1.1.1 
ARG KUBECTL_VERSION=v1.18.5

# Base dependencies
RUN apt update && \
    apt install -y \
      curl=${CURL_VERSION} \
      git=${GIT_VERSION}   \
      jq=${JQ_VERSION} \
      zip=${ZIP_VERSION} \
      make=${MAKE_VERSION} \
&& rm -rf /var/lib/apt/lists/*


# Vault
RUN curl https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip --output vault_${VAULT_VERSION}_linux_amd64.zip &&\
      unzip vault_${VAULT_VERSION}_linux_amd64.zip -d /usr/bin/ && \
      chmod +x /usr/bin/vault && \
      rm -rf vault_${VAULT_VERSION}_linux_amd64.zip

# tfenv (terraform)
RUN git clone -b ${TFENV_VERSION} --single-branch --depth 1 \
      https://github.com/topfreegames/tfenv.git /opt/tfenv && \
      ln -s /opt/tfenv/bin/* /usr/local/bin

# AWS CLI
RUN curl https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o /tmp/awscliv2.zip && \ 
      unzip /tmp/awscliv2.zip -d /tmp/ && \
      ./tmp/aws/install && \
      rm -rf /tmp/awscliv2.zip



# Kubectl
ADD https://storage.googleapis.com/kubernetes-release/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl /bin/kubectl
RUN chmod u+x /bin/kubectl

ENTRYPOINT [ "/bin/bash", "-c" ]
CMD [ "bash" ]
